---
- name: Ensure dependencies are installed.
  yum:
    name: "{{ glusterfs_redhat_release }}"
    state: present

- name: Enable Gluster repository on OracleLinux
  command: "yum-config-manager --enable ol{{ ansible_distribution_major_version }}_gluster5"
  when: ansible_distribution == 'OracleLinux'

- name: Ensure Gluster client package is installed.
  yum:
    name: glusterfs-client
    state: present

- name: Ensure Gluster server packages is installed.
  yum:
    name: glusterfs-server
    state: present
  when: glusterfs_client_only is not defined or not glusterfs_client_only|bool
