---
- name: Ensure PPA for GlusterFS is present.
  apt_repository:
    repo: 'ppa:gluster/glusterfs-{{ glusterfs_ppa_version }}'
    state: present
    update_cache: true
  register: glusterfs_ppa_added
  when: glusterfs_ppa_use

- name: Ensure GlusterFS client will reinstall if the PPA was just added.
  apt:
    name: glusterfs-client
    state: absent
  when: glusterfs_ppa_added.changed
  tags: ['skip_ansible_lint']

- name: Ensure GlusterFS server will reinstall if the PPA was just added.
  apt:
    name: glusterfs-server
    state: absent
  when: glusterfs_ppa_added.changed and glusterfs_client_only is not defined or not glusterfs_client_only|bool
  tags: ['skip_ansible_lint']

- name: Ensure GlusterFS client is installed.
  apt:
    name: glusterfs-client
    state: present
    default_release: "{{ glusterfs_default_release }}"

- name: Ensure GlusterFS server is installed.
  apt:
    name: glusterfs-server
    state: present
    default_release: "{{ glusterfs_default_release }}"
  when: glusterfs_client_only is not defined or not glusterfs_client_only|bool
